language: c
matrix:
  include:
    - compiler: gcc
      os: linux
      dist: focal
      env:
        - RUN_TESTS=yes
        - OPENSC_FROM_GIT=no
        - OPENSC_SYM_HW_CRYPT=yes

addons:
  apt_packages:
    - docbook-xsl
    - libpcsclite-dev
    - xsltproc
    - gengetopt
    - libcmocka-dev
    - help2man
    - pcscd
    - pcsc-tools
    - check
    - ant
    - socat
    - cmake
    - opensc
   
befire_script:
  - if [ "${OPENSC_FROM_GIT}" = "yes" ]; then
       git clone https://github.com/OpenSC/OpenSC;
       set -ex;
       cd OpenSC/;
       ./bootstrap;
       ./configure;
       sudo make install;
       export LD_LIBRARY_PATH=/usr/local/lib;
       cd ${TRAVIS_BUILD_DIR};
    fi

  - if [ "${OPENSC_SYM_HW_CRYPT}" = "yes" ]; then
       git clone https://github.com/popovec/OpenSC;
       set -ex;
       cd OpenSC/;
       git checkout sym_hw_encrypt;
       ./bootstrap;
       ./configure;
       sudo make install;
       export LD_LIBRARY_PATH=/usr/local/lib;
       cd ${TRAVIS_BUILD_DIR};
    fi
    
   
       
script:
  - if [ "${RUN_TESTS}" = "yes" ]; then
       echo $TRAVIS_BUILD_DIR;
       pwd;
       cd src/;
       make -f Makefile.console;
       set -ex;
       
       mkdir tmp;
       socat -d -d pty,link=tmp/OsEIDsim.socket,raw,echo=0 "exec:build/console/console ...,pty,raw,echo=0" &
       PID=$!;
       sleep 1;

       echo "# OsEIDsim" > tmp/reader.conf;
       echo 'FRIENDLYNAME      "OsEIDsim"' >> tmp/reader.conf;
       echo "DEVICENAME        ${TRAVIS_BUILD_DIR}/src/tmp/OsEIDsim.socket" >> tmp/reader.conf;
       echo "LIBPATH           ${TRAVIS_BUILD_DIR}/src/build/console/libOsEIDsim.so.0.0.1" >> tmp/reader.conf;
       echo "CHANNELID         1" >> tmp/reader.conf;
       sudo mv tmp/reader.conf /etc/reader.conf.d/reader.conf;
       cat /etc/reader.conf.d/reader.conf;
       sudo systemctl stop pcscd.service pcscd.socket;
       sudo systemctl start pcscd.service pcscd.socket;
       opensc-tool -l;
       cd $TRAVIS_BUILD_DIR;
       cd tools;
       echo | ./OsEID-tool INIT;
       ./OsEID-tool RSA-CREATE-KEYS;
       ./OsEID-tool RSA-UPLOAD-KEYS;
       ./OsEID-tool RSA-DECRYPT-TEST;
       ./OsEID-tool EC-CREATE-KEYS;
       ./OsEID-tool EC-UPLOAD-KEYS;
       ./OsEID-tool EC-SIGN-TEST;
       ./OsEID-tool EC-ECDH-TEST;
       ./OsEID-tool DES-AES-UPLOAD-KEYS;
       [ "${OPENSC_SYM_HW_CRYPT}" = "yes" ] && ./OsEID-tool AES-TEST;
       kill -9 $PID;
       set +ex;
    fi
